# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2(self):
    self.driver.get("https://webgate.ec.europa.eu/eudamed/secure#/devices/udiDiRegistrationHome")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, ".radio-button-item:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".radio-button-item:nth-child(1) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rw-dropdown-list-value").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rw-list-option:nth-child(1)").click()
    self.driver.find_element(By.ID, "basicUdi-code").click()
    self.driver.find_element(By.ID, "basicUdi-code").send_keys("8907097Q.394.091CV")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .radio-button-group > .radio-button-item:nth-child(1) span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#general-button-save-and-next > span:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,0)")

    #page 2
    #Risk class
    self.driver.find_element(By.CSS_SELECTOR, ".rw-dropdown-list-value").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rw-list-option:nth-child(1)").click()
    #Implantable
    self.driver.find_element(By.CSS_SELECTOR, ".ecl-row:nth-child(2) > .ecl-col > .fieldset-border .eud-u-mr-xs:nth-child(2) > span").click()
    #Measuring Function
    self.driver.find_element(By.CSS_SELECTOR, ".ecl-row:nth-child(3) .eud-u-mr-xs:nth-child(2)").click()
    
    #--------------------------------------------
    self.driver.find_element(By.CSS_SELECTOR, ".eud-u-mr-xs:nth-child(2) #active").click()
    
    self.driver.find_element(By.ID, "active").click()
    
    self.driver.find_element(By.CSS_SELECTOR, ".eud-u-mr-xs:nth-child(2) #administeringMedicine").click()
    #-----------------------------------------------
    #Device Model
    self.driver.find_element(By.ID, "deviceModel").click()
    self.driver.find_element(By.ID, "deviceModel").send_keys("Q.394.091")
    #Device Name
    self.driver.find_element(By.ID, "deviceName").click()
    self.driver.find_element(By.ID, "deviceName").send_keys("Bone forceps, 1.1/2.0mm (for Hand System Instrument Set for Metacarpal & Phalanges Plates)")
    #save and next button
    self.driver.find_element(By.CSS_SELECTOR, "#general-button-save-and-next > span:nth-child(1)").click()

    #Page 3
    self.driver.find_element(By.ID, "udiDiData-0--primaryDi-code").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ecl-row:nth-child(3) .slider:nth-child(2)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ecl-col > .ecl-row:nth-child(2) > .ecl-col")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.execute_script("window.scrollTo(0,215.1999969482422)")
    self.driver.find_element(By.ID, "udiDiData-0--primaryDi-code").click()
    self.driver.find_element(By.ID, "udiDiData-0--primaryDi-code").send_keys("890709734040")
    self.driver.find_element(By.ID, "cndCode").click()
    self.driver.find_element(By.ID, "cndCode").send_keys("L091303")
    self.driver.find_element(By.ID, "general-button-find").click()
    self.driver.find_element(By.ID, "udiDiData-0--tradeName-texts-0--text").click()
    self.driver.find_element(By.ID, "udiDiData-0--tradeName-texts-0--text").send_keys("NET")
    self.driver.find_element(By.CSS_SELECTOR, "#udiDiData-0--tradeName-texts-0--language_input .rw-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rw-list-option:nth-child(7)").click()
    self.driver.find_element(By.ID, "udiDiData-0--reference").click()
    self.driver.find_element(By.ID, "udiDiData-0--reference").send_keys("Q.394.091")
    self.driver.find_element(By.ID, "udiDiData-0--directMarking").click()
    self.driver.find_element(By.CSS_SELECTOR, ".control-label label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".eu-checkbox:nth-child(1) > .no-class > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".eu-checkbox:nth-child(3) span").click()
    self.driver.find_element(By.ID, "udiDiData-0--additionalDescription-texts-0--text").click()
    self.driver.find_element(By.ID, "udiDiData-0--additionalDescription-texts-0--text").send_keys("Bone forceps, 1.1/2.0mm (for Hand System Instrument Set for Metacarpal & Phalanges Plates)")
    self.driver.find_element(By.CSS_SELECTOR, "#udiDiData-0--additionalDescription-texts-0--language_input .svg-inline--fa").click()
    self.driver.find_element(By.CSS_SELECTOR, "#udiDiData-0--additionalDescription-texts-0--language_listbox > .rw-list-option:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".radio-button-item:nth-child(1) span").click()
    self.driver.find_element(By.ID, "general-button-save-and-next").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ignore .label-wizard > span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".done:nth-child(4) .label-wizard > span").click()
    self.driver.find_element(By.ID, "udiDiData-0--primaryDi-code").click()
    self.driver.find_element(By.ID, "udiDiData-0--primaryDi-code").click()
    self.driver.find_element(By.ID, "udiDiData-0--primaryDi-code").send_keys("08907097340400")
    self.driver.find_element(By.CSS_SELECTOR, "#general-button-save-and-next > span:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,2404)")
    self.driver.find_element(By.CSS_SELECTOR, "#deviceWizard > .ecl-row > .ecl-col > .ecl-row:nth-child(1) > .ecl-col").click()
  
