# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://webgate.ec.europa.eu/eudamed/secure#/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "nav-menu-expandable-group-click-2").click()
    self.driver.find_element(By.CSS_SELECTOR, "#device-device-management-menu-register-new-UDI-DI > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".radio-button-item:nth-child(1) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rw-dropdown-list-value").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rw-list-option:nth-child(3)").click()
    self.driver.find_element(By.ID, "basicUdi-code").click()
  
