# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPrint():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_print(self):
    self.driver.get("https://webgate.ec.europa.eu/eudamed/secure#/devices/udiDiRegistrationHome")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "nav-menu-expandable-group-click-3").click()
    self.driver.find_element(By.CSS_SELECTOR, "#priv-device-menu-search-and-view-device > span").click()
    self.driver.find_element(By.ID, "deviceModel").click()
    self.driver.find_element(By.ID, "deviceModel").send_keys("340.010")
    self.driver.find_element(By.CSS_SELECTOR, "#apply-filter > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(3) > .truncate").click()
    self.driver.find_element(By.CSS_SELECTOR, "#basicUdiData > .ecl-col").click()
    self.driver.find_element(By.CSS_SELECTOR, "#device-device-management-device-model-label > span").click()
  
